# Generated by Django 2.2.16 on 2022-04-26 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.SmallIntegerField(default=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(12)], verbose_name='Grade'),
            preserve_default=False,
        ),
    ]
