# Generated by Django 2.2.16 on 2022-04-28 11:20

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220426_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_photo')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True, verbose_name='Sex')),
                ('grade', models.SmallIntegerField(null=True, verbose_name='Grade')),
                ('class_label', models.PositiveSmallIntegerField(null=True, verbose_name='Class label')),
                ('about_me', models.CharField(blank=True, max_length=400, null=True, verbose_name='About Me')),
                ('cell', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Phone Number (optional)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
